services:
  finbot.webapi:
    image: finbot.webapi
    build:
      context: .
      dockerfile: FinBot.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PDbContext: Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=finbot_db
      Seq__ServerUrl: http://seq
      Kafka__BootstrapServers: kafka-1:9092,kafka-2:9092
    ports:
      - "5001:8080"
    depends_on:
      - seq
      - minio
      - postgres
      - kafka-1
      - kafka-2

  finbot.excel:
    image: finbot.excel
    build:
      context: .
      dockerfile: FinBot.ExcelService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PDbContext: Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=finbot_db
      Seq__ServerUrl: http://seq
      MinioOptions__Endpoint: minio:9000
      MinioOptions__AccessKey: minioadmin
      MinioOptions__SecretKey: minioadmin
      Storage__ExcelTablesBucket: excel-tables
      Storage__BarChartsBucket: bar-charts
      Storage__LineChartsBucket: line-charts
      Kafka__BootstrapServers: kafka-1:9092,kafka-2:9092
    ports:
      - "5002:8080"
    depends_on:
      - seq
      - minio
      - postgres
      - kafka-1
      - kafka-2

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finbot_db
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  kafka-1:
    image: apache/kafka:3.8.0
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      
      KAFKA_PROCESS_ROLES: 'broker,controller'
      
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093'
      
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka-1_data:/var/lib/kafka/data
    networks:
      - kafka-cluster
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-2:
    image: apache/kafka:3.8.0
    container_name: kafka-2
    ports:
      - "9094:9092"
      - "9095:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093,2@kafka-2:9093'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka-2_data:/var/lib/kafka/data
    networks:
      - kafka-cluster
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      start_period: 20s
      interval: 5s
      timeout: 10s
      retries: 10
  
  kafka-init:
    image: apache/kafka:3.8.0
    container_name: kafka-init
    networks:
      - kafka-cluster
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    entrypoint: ['/bin/bash', '-c']
    command: |
      "
      TOPICS=(\"llm\" \"excel\" \"bank\" \"api-bank\" \"api-excel\" \"api-llm\" \"dlq\")
      
      for TOPIC in $${TOPICS[@]}; do
        kafka-topics.sh --create --if-not-exists \
          --topic $$TOPIC \
          --partitions 2 \
          --replication-factor 2 \
          --bootstrap-server kafka-1:9092
      done
      "
    profiles:
      - init
      - default

networks:
  kafka-cluster:
    driver: bridge

volumes:
  postgres_data:
  seq_data:
  minio_data:
  redis_data:
  kafka-1_data:
  kafka-2_data: